// livros-react/src/LivroLista.js
import React, { useState, useEffect } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

export default function LivroLista() {
  const controleLivro = new ControleLivro();
  const controleEditora = new ControleEditora();
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      controleLivro.obterLivros().then((result) => {
        setLivros(result);
        setCarregado(true);
      });
    }
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo).then(() => setCarregado(false));
  };

  return (
    <main>
      <h1 className="m-3 text-center">Livros</h1>
      <table className="table table-striped table-hover">
        <thead className="bg-dark">
          <tr className="text-center text-light">
            <th>Ações</th>
            <th>Código</th>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro key={index} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
}

function LinhaLivro(props) {
  const controleEditora = new ControleEditora();
  const nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);

  return (
    <tr>
      <td className="text-center align-middle">
        <button
          className="btn btn-danger"
          onClick={() => props.excluir(props.livro.codigo)}
        >
          Excluir
        </button>
      </td>
      <td className="text-center align-middle">{props.livro.codigo}</td>
      <td className="text-center align-middle">{props.livro.titulo}</td>
      <td className="text-center align-middle">{props.livro.resumo}</td>
      <td className="text-center align-middle">{nomeEditora}</td>
      <td className="text-center align-middle">
        <ul>
          {props.livro.autores.map((autor, index) => (
            <li className="text-center" key={index}>
              {autor}
            </li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

// livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivroService from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivroService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: string) => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  };

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora.toString());
  };
}

<main class="container">
    <h1 class="text-center">Catálogo de Livros</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr class="bg-dark text-light text-center">
                <th>Ações</th>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros" class="text-center align-middle">
                <td><button class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">
                        Excluir
                    </button></td>
                <td>{{ livro.titulo }}</td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
