// livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivroService from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivroService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: string) => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  };

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora.toString());
  };
}

<main class="container">
    <h1 class="text-center">Catálogo de Livros</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr class="bg-dark text-light text-center">
                <th>Ações</th>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros" class="text-center align-middle">
                <td><button class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">
                        Excluir
                    </button></td>
                <td>{{ livro.titulo }}</td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// livros-next/src/pages/LivroLista.tsx
import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Menu } from "../componentes/Menu";
import styles from "../styles/Home.module.css";
import { LinhaLivro } from "../componentes/LinhaLivro";
import Livro from "../classes/modelo/Livro";
import ControleLivro from "@/classes/controle/ControleLivro";

const LivroLista: React.FC = () => {
  const controleLivros = new ControleLivro();
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>(false);

  useEffect(() => {
    if (!carregado) {
      controleLivros.obterLivros().then((dados) => {
        setLivros(dados);
        setCarregado(true);
      });
    }
  }, [carregado]);

  const excluir = async (codigo: string) => {
    await controleLivros.excluir(codigo);
    setCarregado(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Livros</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div className="p-5">
        <h1 className={styles.title}>Livros</h1>
        <table className="table table-hover">
          <thead className="bg-dark">
            <tr className="text-center text-light">
              <th scope="col">Ações</th>
              <th scope="col">Código</th>
              <th scope="col">Título</th>
              <th scope="col">Resumo</th>
              <th scope="col">Editora</th>
              <th scope="col">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro key={index} livro={livro} excluir={excluir} />
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default LivroLista;
