// livros-react/src/LivroDados.js
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

export default function LivroDados() {
  const controleLivro = new ControleLivro();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();
    const livro = {
      titulo: titulo,
      resumo: resumo,
      autores: autores.split("\n"),
      codEditora: codEditora,
    };
    controleLivro.incluir(livro).then(() => navigate("/"));
  };

  return (
    <main>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">
            Título
          </label>
          <input
            type="text"
            className="form-control"
            id="titulo"
            value={titulo}
            onChange={(event) => setTitulo(event.target.value)}
          />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">
            Resumo
          </label>
          <textarea
            className="form-control"
            id="resumo"
            rows="3"
            value={resumo}
            onChange={(event) => setResumo(event.target.value)}
          ></textarea>
        </div>

        <div className="mb-3">
          <label htmlFor="codEditora" className="form-label">
            Editora
          </label>
          <select
            className="form-select"
            id="codEditora"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">
            Autores (1 por linha)
          </label>
          <textarea
            className="form-control"
            id="autores"
            rows="3"
            value={autores}
            onChange={(event) => setAutores(event.target.value)}
          ></textarea>
        </div>
        <button type="submit" className="btn btn-primary">
          Salvar Dados
        </button>
      </form>
    </main>
  );
}

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('0', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split(/\r?\n/);
    this.servLivros.incluir(this.livro).then(() => {
      // Use the async version of the incluir method
      this.router.navigateByUrl('/lista');
    });
  };
}

<main class="container">
    <h1>Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group my-2">
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" name="titulo" class="form-control"
                [(ngModel)]="livro.titulo" required>
        </div>
        <div class="form-group my-2">
            <label for="resumo">Resumo:</label>
            <textarea id="resumo" name="resumo" class="form-control"
                [(ngModel)]="livro.resumo"></textarea>
        </div>
        <div class="form-group my-2">
            <label for="editora">Editora:</label>
            <select id="editora" name="editora" class="form-control"
                [(ngModel)]="livro.codEditora" required>
                <option *ngFor="let e of editoras" [value]="e.codEditora">{{e.nome}}</option>
            </select>
        </div>
        <div class="form-group my-2">
            <label for="autores">Autores:</label>
            <textarea id="autores" name="autores" class="form-control"
                [(ngModel)]="autoresForm"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Incluir</button>
    </form>
</main>
