// livros-next/src/pages/LivroDados.tsx
import { useState } from "react";
import { useRouter } from "next/router";
import ControleLivro from "../classes/controle/ControleLivro";
import ControleEditora from "../classes/controle/ControleEditora";
import styles from "../styles/Home.module.css";
import Livro from "@/classes/modelo/Livro";
import Head from "next/head";
import { Menu } from "../componentes/Menu";

export default function LivroDados() {
  const controleEditora = new ControleEditora();
  const controleLivros = new ControleLivro();
  const router = useRouter();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro = new Livro(
      "",
      codEditora,
      titulo,
      resumo,
      autores.split("\n")
    );
    controleLivros.incluir(livro).then(() => {
      router.push("/LivroLista");
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Cadastro de Livros</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />

      <form onSubmit={incluir} className="p-5">
        <h1>Cadastro de Livros</h1>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">
            Título
          </label>
          <input
            type="text"
            className="form-control"
            id="titulo"
            value={titulo}
            onChange={(event) => setTitulo(event.target.value)}
          />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">
            Resumo
          </label>
          <textarea
            className="form-control"
            id="resumo"
            rows={3}
            value={resumo}
            onChange={(event) => setResumo(event.target.value)}
          ></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="codEditora" className="form-label">
            Editora
          </label>
          <select
            className="form-select"
            id="codEditora"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">
            Autores (1 por linha)
          </label>
          <textarea
            className="form-control"
            id="autores"
            rows={3}
            value={autores}
            onChange={(event) => setAutores(event.target.value)}
          ></textarea>
        </div>
        <button type="submit" className="btn btn-primary">
          Salvar Dados
        </button>
      </form>
    </div>
  );
}

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('0', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split(/\r?\n/);
    this.servLivros.incluir(this.livro).then(() => {
      // Use the async version of the incluir method
      this.router.navigateByUrl('/lista');
    });
  };
}

<main class="container">
    <h1>Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group my-2">
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" name="titulo" class="form-control"
                [(ngModel)]="livro.titulo" required>
        </div>
        <div class="form-group my-2">
            <label for="resumo">Resumo:</label>
            <textarea id="resumo" name="resumo" class="form-control"
                [(ngModel)]="livro.resumo"></textarea>
        </div>
        <div class="form-group my-2">
            <label for="editora">Editora:</label>
            <select id="editora" name="editora" class="form-control"
                [(ngModel)]="livro.codEditora" required>
                <option *ngFor="let e of editoras" [value]="e.codEditora">{{e.nome}}</option>
            </select>
        </div>
        <div class="form-group my-2">
            <label for="autores">Autores:</label>
            <textarea id="autores" name="autores" class="form-control"
                [(ngModel)]="autoresForm"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Incluir</button>
    </form>
</main>
